# Generated by Django 5.1.1 on 2025-05-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='token',
            name='unique_confirmation_code_for_user',
        ),
        migrations.RemoveField(
            model_name='token',
            name='confirmation_code',
        ),
    ]
