# Generated by Django 5.1.1 on 2025-05-21 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_token_unique_confirmation_code_for_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
