# Generated by Django 5.1.1 on 2025-05-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_bio_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SlugField(choices=[('user', 'U'), ('moderator', 'M'), ('admin', 'A')], default='user', verbose_name='Роль'),
        ),
    ]
