# Generated by Django 5.1.1 on 2025-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='confirmation_code',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
