# Generated by Django 5.1.1 on 2025-05-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_token_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='confirmation_code',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
