# Generated by Django 5.1.1 on 2025-05-22 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_token_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\Z'), django.core.validators.RegexValidator(message='Запрещено использовать me в качестве имени пользователя!', regex='^(?!me$)')]),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
