# Generated by Django 5.1.1 on 2025-05-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_bio_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',)},
        ),
    ]
