# Generated by Django 5.1.1 on 2025-05-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author_id',
            new_name='author',
        ),
    ]
