# Generated by Django 5.1.1 on 2025-05-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_category_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
